<?php

namespace jweb\gii\crud\providers;

class DateTimeProvider extends \jweb\gii\base\Provider
{
    public function activeField($attribute)
    {
        $column = $this->generator->getTableSchema()->columns[$attribute->name];

        switch (true) {
            case (in_array($column->name, $this->columnNames)):
                $this->generator->requires[] = 'kartik-v/yii2-widget-datepicker';
                return "
                  \$form->field(\$model, '{$column->name}')->widget(\kartik\datecontrol\DateControl::classname(), [
                      'type' => \kartik\datecontrol\DateControl::FORMAT_DATETIME
                  ]);
                 ";
                break;
            default:
                return null;
        }
    }
        public function columnFormat($column, $model) {
    
        if (in_array($column->name, $this->columnNames)) {
            $method = __METHOD__;
            $code = <<<EOS
// generated by {$method}
[
                   "class" => DataColumn::className(),
                  'filterType' => GridView::FILTER_DATETIME,
                  "attribute" => "{$column->name}",
                  'format' => ['date', 'php:Y-m-d H:i:s'],
]
EOS;
            return $code;
        }
    }

} 
